// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Engine.API.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace Engine.API.Models
{
    public partial class ProductDescription
    {
        private string _description;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private DateTimeOffset? _modifiedDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? ModifiedDate
        {
            get { return this._modifiedDate; }
            set { this._modifiedDate = value; }
        }
        
        private int? _productDescriptionID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ProductDescriptionID
        {
            get { return this._productDescriptionID; }
            set { this._productDescriptionID = value; }
        }
        
        private IList<ProductModelProductDescription> _productModelProductDescriptions;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<ProductModelProductDescription> ProductModelProductDescriptions
        {
            get { return this._productModelProductDescriptions; }
            set { this._productModelProductDescriptions = value; }
        }
        
        private string _rowguid;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Rowguid
        {
            get { return this._rowguid; }
            set { this._rowguid = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ProductDescription class.
        /// </summary>
        public ProductDescription()
        {
            this.ProductModelProductDescriptions = new LazyList<ProductModelProductDescription>();
        }
        
        /// <summary>
        /// Initializes a new instance of the ProductDescription class with
        /// required arguments.
        /// </summary>
        public ProductDescription(string description)
            : this()
        {
            if (description == null)
            {
                throw new ArgumentNullException("description");
            }
            this.Description = description;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken descriptionValue = inputObject["Description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken modifiedDateValue = inputObject["ModifiedDate"];
                if (modifiedDateValue != null && modifiedDateValue.Type != JTokenType.Null)
                {
                    this.ModifiedDate = ((DateTimeOffset)modifiedDateValue);
                }
                JToken productDescriptionIDValue = inputObject["ProductDescriptionID"];
                if (productDescriptionIDValue != null && productDescriptionIDValue.Type != JTokenType.Null)
                {
                    this.ProductDescriptionID = ((int)productDescriptionIDValue);
                }
                JToken productModelProductDescriptionsSequence = ((JToken)inputObject["ProductModelProductDescriptions"]);
                if (productModelProductDescriptionsSequence != null && productModelProductDescriptionsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken productModelProductDescriptionsValue in ((JArray)productModelProductDescriptionsSequence))
                    {
                        ProductModelProductDescription productModelProductDescription = new ProductModelProductDescription();
                        productModelProductDescription.DeserializeJson(productModelProductDescriptionsValue);
                        this.ProductModelProductDescriptions.Add(productModelProductDescription);
                    }
                }
                JToken rowguidValue = inputObject["rowguid"];
                if (rowguidValue != null && rowguidValue.Type != JTokenType.Null)
                {
                    this.Rowguid = ((string)rowguidValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type ProductDescription
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.Description == null)
            {
                throw new ArgumentNullException("Description");
            }
            if (this.Description != null)
            {
                outputObject["Description"] = this.Description;
            }
            if (this.ModifiedDate != null)
            {
                outputObject["ModifiedDate"] = this.ModifiedDate.Value;
            }
            if (this.ProductDescriptionID != null)
            {
                outputObject["ProductDescriptionID"] = this.ProductDescriptionID.Value;
            }
            JArray productModelProductDescriptionsSequence = null;
            if (this.ProductModelProductDescriptions != null)
            {
                if (this.ProductModelProductDescriptions is ILazyCollection<ProductModelProductDescription> == false || ((ILazyCollection<ProductModelProductDescription>)this.ProductModelProductDescriptions).IsInitialized)
                {
                    productModelProductDescriptionsSequence = new JArray();
                    outputObject["ProductModelProductDescriptions"] = productModelProductDescriptionsSequence;
                    foreach (ProductModelProductDescription productModelProductDescriptionsItem in this.ProductModelProductDescriptions)
                    {
                        if (productModelProductDescriptionsItem != null)
                        {
                            productModelProductDescriptionsSequence.Add(productModelProductDescriptionsItem.SerializeJson(null));
                        }
                    }
                }
            }
            if (this.Rowguid != null)
            {
                outputObject["rowguid"] = this.Rowguid;
            }
            return outputObject;
        }
    }
}
