// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Engine.API.Models
{
    public partial class ProductCategoryDTO
    {
        private DateTimeOffset? _modifiedDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? ModifiedDate
        {
            get { return this._modifiedDate; }
            set { this._modifiedDate = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private string _parentProductCategoryID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string ParentProductCategoryID
        {
            get { return this._parentProductCategoryID; }
            set { this._parentProductCategoryID = value; }
        }
        
        private int? _productCategoryID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ProductCategoryID
        {
            get { return this._productCategoryID; }
            set { this._productCategoryID = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ProductCategoryDTO class.
        /// </summary>
        public ProductCategoryDTO()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken modifiedDateValue = inputObject["ModifiedDate"];
                if (modifiedDateValue != null && modifiedDateValue.Type != JTokenType.Null)
                {
                    this.ModifiedDate = ((DateTimeOffset)modifiedDateValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken parentProductCategoryIDValue = inputObject["ParentProductCategoryID"];
                if (parentProductCategoryIDValue != null && parentProductCategoryIDValue.Type != JTokenType.Null)
                {
                    this.ParentProductCategoryID = ((string)parentProductCategoryIDValue);
                }
                JToken productCategoryIDValue = inputObject["ProductCategoryID"];
                if (productCategoryIDValue != null && productCategoryIDValue.Type != JTokenType.Null)
                {
                    this.ProductCategoryID = ((int)productCategoryIDValue);
                }
            }
        }
    }
}
