// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Engine.API.Models;
using Newtonsoft.Json.Linq;

namespace Engine.API.Models
{
    public partial class SalesOrderDetail
    {
        private double? _lineTotal;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? LineTotal
        {
            get { return this._lineTotal; }
            set { this._lineTotal = value; }
        }
        
        private DateTimeOffset? _modifiedDate;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? ModifiedDate
        {
            get { return this._modifiedDate; }
            set { this._modifiedDate = value; }
        }
        
        private int? _orderQty;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? OrderQty
        {
            get { return this._orderQty; }
            set { this._orderQty = value; }
        }
        
        private Product _product;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Product Product
        {
            get { return this._product; }
            set { this._product = value; }
        }
        
        private int? _productID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ProductID
        {
            get { return this._productID; }
            set { this._productID = value; }
        }
        
        private string _rowguid;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Rowguid
        {
            get { return this._rowguid; }
            set { this._rowguid = value; }
        }
        
        private int? _salesOrderDetailID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? SalesOrderDetailID
        {
            get { return this._salesOrderDetailID; }
            set { this._salesOrderDetailID = value; }
        }
        
        private int? _salesOrderID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? SalesOrderID
        {
            get { return this._salesOrderID; }
            set { this._salesOrderID = value; }
        }
        
        private double? _unitPrice;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? UnitPrice
        {
            get { return this._unitPrice; }
            set { this._unitPrice = value; }
        }
        
        private double? _unitPriceDiscount;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public double? UnitPriceDiscount
        {
            get { return this._unitPriceDiscount; }
            set { this._unitPriceDiscount = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the SalesOrderDetail class.
        /// </summary>
        public SalesOrderDetail()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken lineTotalValue = inputObject["LineTotal"];
                if (lineTotalValue != null && lineTotalValue.Type != JTokenType.Null)
                {
                    this.LineTotal = ((double)lineTotalValue);
                }
                JToken modifiedDateValue = inputObject["ModifiedDate"];
                if (modifiedDateValue != null && modifiedDateValue.Type != JTokenType.Null)
                {
                    this.ModifiedDate = ((DateTimeOffset)modifiedDateValue);
                }
                JToken orderQtyValue = inputObject["OrderQty"];
                if (orderQtyValue != null && orderQtyValue.Type != JTokenType.Null)
                {
                    this.OrderQty = ((int)orderQtyValue);
                }
                JToken productValue = inputObject["Product"];
                if (productValue != null && productValue.Type != JTokenType.Null)
                {
                    Product product = new Product();
                    product.DeserializeJson(productValue);
                    this.Product = product;
                }
                JToken productIDValue = inputObject["ProductID"];
                if (productIDValue != null && productIDValue.Type != JTokenType.Null)
                {
                    this.ProductID = ((int)productIDValue);
                }
                JToken rowguidValue = inputObject["rowguid"];
                if (rowguidValue != null && rowguidValue.Type != JTokenType.Null)
                {
                    this.Rowguid = ((string)rowguidValue);
                }
                JToken salesOrderDetailIDValue = inputObject["SalesOrderDetailID"];
                if (salesOrderDetailIDValue != null && salesOrderDetailIDValue.Type != JTokenType.Null)
                {
                    this.SalesOrderDetailID = ((int)salesOrderDetailIDValue);
                }
                JToken salesOrderIDValue = inputObject["SalesOrderID"];
                if (salesOrderIDValue != null && salesOrderIDValue.Type != JTokenType.Null)
                {
                    this.SalesOrderID = ((int)salesOrderIDValue);
                }
                JToken unitPriceValue = inputObject["UnitPrice"];
                if (unitPriceValue != null && unitPriceValue.Type != JTokenType.Null)
                {
                    this.UnitPrice = ((double)unitPriceValue);
                }
                JToken unitPriceDiscountValue = inputObject["UnitPriceDiscount"];
                if (unitPriceDiscountValue != null && unitPriceDiscountValue.Type != JTokenType.Null)
                {
                    this.UnitPriceDiscount = ((double)unitPriceDiscountValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type SalesOrderDetail
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.LineTotal != null)
            {
                outputObject["LineTotal"] = this.LineTotal.Value;
            }
            if (this.ModifiedDate != null)
            {
                outputObject["ModifiedDate"] = this.ModifiedDate.Value;
            }
            if (this.OrderQty != null)
            {
                outputObject["OrderQty"] = this.OrderQty.Value;
            }
            if (this.Product != null)
            {
                outputObject["Product"] = this.Product.SerializeJson(null);
            }
            if (this.ProductID != null)
            {
                outputObject["ProductID"] = this.ProductID.Value;
            }
            if (this.Rowguid != null)
            {
                outputObject["rowguid"] = this.Rowguid;
            }
            if (this.SalesOrderDetailID != null)
            {
                outputObject["SalesOrderDetailID"] = this.SalesOrderDetailID.Value;
            }
            if (this.SalesOrderID != null)
            {
                outputObject["SalesOrderID"] = this.SalesOrderID.Value;
            }
            if (this.UnitPrice != null)
            {
                outputObject["UnitPrice"] = this.UnitPrice.Value;
            }
            if (this.UnitPriceDiscount != null)
            {
                outputObject["UnitPriceDiscount"] = this.UnitPriceDiscount.Value;
            }
            return outputObject;
        }
    }
}
